# Generated by Django 6.0 on 2026-01-24 10:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='branch',
            name='close_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='branch',
            name='open_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='branch',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'start_time', 'status'], name='api_appoint_branch__11cd6c_idx'), models.Index(fields=['user', 'start_time', 'status'], name='api_appoint_user_id_74a379_idx')],
            },
        ),
    ]
